version: '3.8'

services:
  loveloveparadise:
    build: .
    volumes:
      - .:/usr/local/apache2/htdocs/
    environment:
      - VIRTUAL_HOST=loveloveparadise.kro.kr  # 도메인 연결을 위한 환경 변수 설정
    networks:
      - reverse-proxy_proxy  # nginx-proxy 네트워크와 연결

networks:
  reverse-proxy_proxy:
    external: true